from database import lang_db

CVE_MESSAGES = {
    "PTBR": {
        "pkg_modal": {
            "title": "Pesquisar CVEs",
            "lbl_score": "Score CVSS",
            "desc_score": "Filtre por severidade / pontuação",
            "ph_score": "Selecione a faixa de score",
            "opt_low": "Baixo (0.1 - 3.9)",
            "opt_medium": "Médio (4.0 - 6.9)",
            "opt_high": "Alto (7.0 - 8.9)",
            "opt_critical": "Crítico (9.0 - 10.0)",
            "lbl_year": "Intervalo de Tempo",
            "desc_year": "Escolha o ano de publicação",
            "ph_year": "Selecione o ano",
            "lbl_package": "Pacote ou Termo",
            "desc_package": "Insira o nome do pacote ou palavra-chave",
            "ph_package": "Ex: linux, openssl, sudo...",
            "not_found": "Nenhum CVE encontrado para o pacote `{package}` em {year} com severidade `{severity}`.",
            "error": "Algo deu errado na consulta!",
        },
        "id_modal": {
            "title": "Pesquisar CVE",
            "lbl_id": "ID da CVE",
            "ph_id": "Ex: CVE-2021-44228",
            "invalid_format": "Formato de CVE inválido! Use o formato `CVE-AAAA-NNNN` (ex: `CVE-2021-44228`).",
            "not_found": "Nenhum registro encontrado para a CVE `{cve_code}`.",
            "error": "Algo deu errado na consulta!",
        },
        "detail_view": {
            "details_title": "🛡️ **Detalhes da {cve_id}**",
            "status": "Status",
            "published": "Publicado em",
            "updated": "Atualizado",
            "score": "Pontuação",
            "vector": "Vetor",
            "description": "Descrição",
            "no_description": "Sem descrição disponível.",
            "ref_single": "Link de Origem",
            "ref_multiple": "Link de Origem {idx}",
            "load_error": "Não foi possível carregar os detalhes da `{cve_id}`.",
        },
        "panel_view": {
            "btn_details": "Ver Detalhes",
            "score": "Score",
            "published": "Publicado em",
            "description": "Descrição",
            "no_description": "Sem descrição disponível.",
            "btn_prev": "◀ Anteriores",
            "btn_next": "Próximos ▶",
            "page_indicator": "Página {page}",
            "error_update": "Algo deu errado ao atualizar o painel!",
        },
    },
    "ES": {
        "pkg_modal": {
            "title": "Buscar CVEs",
            "lbl_score": "Puntuación CVSS",
            "desc_score": "Filtrar por severidad / puntuación",
            "ph_score": "Seleccione el rango de puntuación",
            "opt_low": "Bajo (0.1 - 3.9)",
            "opt_medium": "Medio (4.0 - 6.9)",
            "opt_high": "Alto (7.0 - 8.9)",
            "opt_critical": "Crítico (9.0 - 10.0)",
            "lbl_year": "Rango de Tiempo",
            "desc_year": "Elija el año de publicación",
            "ph_year": "Seleccione el año",
            "lbl_package": "Paquete o Término",
            "desc_package": "Ingrese el nombre del paquete o palabra clave",
            "ph_package": "Ej: linux, openssl, sudo...",
            "not_found": "No se encontraron CVEs para el paquete `{package}` en {year} con severidad `{severity}`.",
            "error": "¡Algo salió mal en la consulta!",
        },
        "id_modal": {
            "title": "Buscar CVE",
            "lbl_id": "ID del CVE",
            "ph_id": "Ej: CVE-2021-44228",
            "invalid_format": "¡Formato de CVE inválido! Use el formato `CVE-AAAA-NNNN` (ej: `CVE-2021-44228`).",
            "not_found": "No se encontraron registros para el CVE `{cve_code}`.",
            "error": "¡Algo salió mal en la consulta!",
        },
        "detail_view": {
            "details_title": "🛡️ **Detalles de {cve_id}**",
            "status": "Estado",
            "published": "Publicado el",
            "updated": "Actualizado",
            "score": "Puntuación",
            "vector": "Vector",
            "description": "Descripción",
            "no_description": "Sin descripción disponible.",
            "ref_single": "Enlace de Origen",
            "ref_multiple": "Enlace de Origen {idx}",
            "load_error": "No se pudieron cargar los detalles de `{cve_id}`.",
        },
        "panel_view": {
            "btn_details": "Ver Detalles",
            "score": "Puntuación",
            "published": "Publicado el",
            "description": "Descripción",
            "no_description": "Sin descripción disponible.",
            "btn_prev": "◀ Anteriores",
            "btn_next": "Siguientes ▶",
            "page_indicator": "Página {page}",
            "error_update": "¡Algo salió mal al actualizar el panel!",
        },
    },
    "EN": {
        "pkg_modal": {
            "title": "Search CVEs",
            "lbl_score": "CVSS Score",
            "desc_score": "Filter by severity / score",
            "ph_score": "Select score range",
            "opt_low": "Low (0.1 - 3.9)",
            "opt_medium": "Medium (4.0 - 6.9)",
            "opt_high": "High (7.0 - 8.9)",
            "opt_critical": "Critical (9.0 - 10.0)",
            "lbl_year": "Time Range",
            "desc_year": "Choose publication year",
            "ph_year": "Select year",
            "lbl_package": "Package or Term",
            "desc_package": "Enter package name or keyword",
            "ph_package": "Ex: linux, openssl, sudo...",
            "not_found": "No CVEs found for package `{package}` in {year} with severity `{severity}`.",
            "error": "Something went wrong with the query!",
        },
        "id_modal": {
            "title": "Search CVE",
            "lbl_id": "CVE ID",
            "ph_id": "Ex: CVE-2021-44228",
            "invalid_format": "Invalid CVE format! Use `CVE-YYYY-NNNN` format (ex: `CVE-2021-44228`).",
            "not_found": "No records found for CVE `{cve_code}`.",
            "error": "Something went wrong with the query!",
        },
        "detail_view": {
            "details_title": "🛡️ **Details for {cve_id}**",
            "status": "Status",
            "published": "Published on",
            "updated": "Updated",
            "score": "Score",
            "vector": "Vector",
            "description": "Description",
            "no_description": "No description available.",
            "ref_single": "Source Link",
            "ref_multiple": "Source Link {idx}",
            "load_error": "Could not load details for `{cve_id}`.",
        },
        "panel_view": {
            "btn_details": "View Details",
            "score": "Score",
            "published": "Published on",
            "description": "Description",
            "no_description": "No description available.",
            "btn_prev": "◀ Previous",
            "btn_next": "Next ▶",
            "page_indicator": "Page {page}",
            "error_update": "Something went wrong updating the panel!",
        },
    },
}

async def cvecog_translate(guild_id, *keys, **kwargs):
    result = CVE_MESSAGES[await lang_db.get_language(guild_id, default="EN")]
    for key in keys:
        result = result[key]
    return result.format(**kwargs)